
# The IP Address in which the server will be hosted.
address = "127.0.0.1"
port = 7878

# Admin User
# CHANGE THESE!
admin_user = "Admin"
admin_pass = "pass"

# Basic User
# CHANGE THESE!
main_user = "User"
main_pass = "pass"

[[runnables]]
name = "Numbers"
path = "./run.sh"

[[runnables]]
name = "Numbers 2"
path = "./run.sh"
